---

- hosts: all
  gather_facts: no

  vars:


    dbUsername: root
    dbPassword: MySecureP@ssw0rd


  tasks:

    - name: send config to server
      template:
        src: hello_world.jn2
        dest: /home/ubuntu/config.ini