---

- hosts: all
  gather_facts: no




  tasks:

    - name: Read CSV
      read_csv:
        path: users.csv
        skipinitialspace: yes
      register: csv_users 
      delegate_to: localhost


    - name: Iterate users
      debug:
        msg: "Hello, {{ userEmailInfo.first_name }} {{ userEmailInfo.last_name }} : {{ userEmailInfo.email }}"
      loop: "{{ csv_users.list }}"
      loop_control:
        loop_var: userEmailInfo
    
