---

- hosts: webservers
  name: A play with variables
  gather_facts: no

  vars:
    first_name: John
    family: Doe

  tasks:
    - name: Print first name variable
      debug:
        var: first_name

    - name: Print family variable with message
      debug:
        msg: "Hello, {{ family }}"

    - name: Print both variables
      debug:
        msg: "{{ first_name }}, {{ family }}"