---

- hosts: webserver
  become: yes
  become_user: root
  gather_facts: no

  vars_prompt:

    - name: username
      prompt: Enter username:
      default: admin

    - name: password
      prompt: Enter the password:
      default: password
      private: true

  vars:
    pkgname: nginx
    trivera_tech: Andy


  tasks:
    - name: Install "{{ pkgname }}"
      apt:
        name: "{{ pkgname }}"
        state: present

    - name: Print Some variables
      debug:
        msg: "Hello, {{ trivera_tech }}"

    - name: Print Some variables
      debug:
        msg: "Hello, {{ username }}"

    - name: Print Some variables
      debug:
        msg: "Hello, {{ password }}"

    - name: Remove "{{ pkgname }}"
      apt:
        name: "{{ pkgname }}"
        state: absent
        autoremove: yes
