---

- hosts: webserver
  gather_facts: no

  vars:
    pkgname: nginx
    trivera_tech: Andy


  tasks:

    - name: Print Some variables
      debug:
        msg: "Hello, {{ trivera_tech }}"

    - name: Print Some variables
      debug:
        msg: "Hello, {{ pkgname }}"

    - name: Print Some variables
      debug:
        msg: "{{ trivera_tech }}, {{ password }}"
