---

- name: Conditional play
  gather_facts: no 
  hosts: webservers

  vars_prompt:

    - name: question
      prompt: enter a value (yes/no)
      private: no
      default: yes


  vars:
    epic: true
    distro: "Ubuntu"

  tasks:

    #TODO: Add validation for question variable (Student task)

    - name: "Print if question is true"
      when: 
        - question | bool  
        - distro == "Ubuntu"

      debug: 
        msg: "Task 1"

    - name: "print if question is false"
      when: not question | bool  or epic
      debug:
        msg: "Task 2"
      




