---

- hosts: webservers
  gather_facts: no

  vars:
    new_timezone: "Europe/Berlin"

  tasks:

    - name: Access timezone and register its value
      shell: cat /etc/timezone
      register: remote_timezone

    - debug:
        msg: "{{ remote_timezone.stdout }}"

    - name: update timezone
      shell: echo "{{ new_timezone }}" > /etc/timezone
      become: yes
      become_user: root
      when: remote_timezone.stdout !=  new_timezone
      notify:
        - succ_msg
        - succ_msg_b

  handlers:

    - name: succ_msg
      debug: msg="Timezone has been updated to {{ new_timezone }}"

    - name: succ_msg_b
      debug: msg="Timezone has been updated to {{ new_timezone }} Finish"

