---

- hosts: webservers

  vars_prompt:

    - name: userCount
      prompt: How many users
      private: no

  vars:

    dbUsername: root
    dbPassword: mySecurePassword
    names:
      - John
      - Jane
      - Sarah
      - Tim

  tasks:

    - name: Send Config to servers
      template:
        src: config.ini.jn2
        dest: ~/config.ini