---

- name: Demonstrate register usage with file creation
  hosts: webservers
  gather_facts: no

  tasks:
    - name: Create a test file
      copy:
        content: "Sample text for testing."
        dest: /home/ubuntu/a.txt

    - name: Capture file content
      shell: cat /home/ubuntu/a.txt
      register: file_content

    - name: Display file content
      debug:
        msg: "{{ file_content.stdout }}"